# Configures canister-rkt tests at Travis CI (https://travis-ci.org).

language: golang

go:
 - 1.3

before_install:
 - export GOROOT=/usr/local/go
 - export GOPATH=$canister-rkt/go
 - export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
 - git clone https://github.com/coreos/rocket.git
 - cd rocket
 - ./build
 - sudo apt-get install -y cpio realpath squashfs-tools

install:
 - go get github.com/appc/spec/...

script:
 - ./test
