# Configures canister-rkt tests at Travis CI (https://travis-ci.org).

language: golang

go:
 - 1.3

before_install:
 - git clone https://github.com/coreos/rocket.git
 - cd rocket
 - ./build
 - sudo apt-get update -qq
 - sudo apt-get install -y cpio realpath squashfs-tools

install:
 - go get github.com/appc/spec/...

script:
 - ./test
